spring:
  application:
    name: raffle-backend

  datasource:
    # When your app runs on your laptop:
    url: jdbc:postgresql://localhost:${PGPORT:5433}/${PGDATABASE:raffle}
    username: ${PGUSER:admin}
    # DO NOT commit a password. Supply at runtime (see Step 4).
    password: ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none          # Flyway controls schema
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC   # align with DB UTC
  jackson:
    time-zone: UTC            # serialize as UTC by default (still ISO-8601)

  flyway:
    enabled: true
    locations: classpath:db/migration
    # baseline-on-migrate: true  # only if adopting an existing schema

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

# Helpful SQL logs for local dev; comment out if noisy
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: warn
